{"hierarchy":{"paths":[[]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK"},"variants":[{"paths":["\/documentation\/onmobilegamificationsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/onmobilegamificationsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/AddEventRewardModel","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/BadgeTransDetail","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/BadgeTransactionModel","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/BadgeTransactionStyle","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationClientHandler","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/PollInfoViewModel","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/Reward","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/RewardHistoryModel","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/UserReferRegistrationModel"],"anchor":"Classes","generated":true},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/Gamification","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationClientCallback"],"anchor":"Structures","generated":true},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationCallBackListenerType","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationError","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationEventListenerType","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/ViewDisplayType"],"anchor":"Enumerations","generated":true}],"metadata":{"modules":[{"name":"OnMobileGamificationSDK"}],"title":"OnMobileGamificationSDK","externalID":"OnMobileGamificationSDK","roleHeading":"Framework","symbolKind":"module","role":"collection"},"references":{"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/GamificationEventListenerType":{"title":"GamificationEventListenerType","url":"\/documentation\/onmobilegamificationsdk\/gamificationeventlistenertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GamificationEventListenerType"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationEventListenerType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GamificationEventListenerType"}],"abstract":[{"text":"Details of the available Event types","type":"text"}]},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/RewardHistoryModel":{"navigatorTitle":[{"text":"RewardHistoryModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/RewardHistoryModel","title":"RewardHistoryModel","kind":"symbol","abstract":[{"type":"text","text":"Provides the complete detail of rewards history"}],"url":"\/documentation\/onmobilegamificationsdk\/rewardhistorymodel","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RewardHistoryModel","kind":"identifier"}]},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/ViewDisplayType":{"url":"\/documentation\/onmobilegamificationsdk\/viewdisplaytype","type":"topic","title":"ViewDisplayType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewDisplayType"}],"navigatorTitle":[{"kind":"identifier","text":"ViewDisplayType"}],"abstract":[{"type":"text","text":"Details of all available view display types"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/ViewDisplayType"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/OnMobileGamificationSDKVersionNumber":{"url":"\/documentation\/onmobilegamificationsdk\/onmobilegamificationsdkversionnumber","type":"topic","role":"symbol","fragments":[{"text":"OnMobileGamificationSDKVersionNumber","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"OnMobileGamificationSDKVersionNumber","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/OnMobileGamificationSDKVersionNumber"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/PollInfoViewModel":{"url":"\/documentation\/onmobilegamificationsdk\/pollinfoviewmodel","navigatorTitle":[{"text":"PollInfoViewModel","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/PollInfoViewModel","kind":"symbol","type":"topic","title":"PollInfoViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PollInfoViewModel","kind":"identifier"}],"abstract":[{"text":"Provides the complere information about the poll","type":"text"}]},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/Reward":{"title":"Reward","navigatorTitle":[{"text":"Reward","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/Reward","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Provides the complete detail of reward"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Reward","kind":"identifier"}],"url":"\/documentation\/onmobilegamificationsdk\/reward"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/BadgeTransactionStyle":{"type":"topic","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/BadgeTransactionStyle","kind":"symbol","url":"\/documentation\/onmobilegamificationsdk\/badgetransactionstyle","navigatorTitle":[{"text":"BadgeTransactionStyle","kind":"identifier"}],"title":"BadgeTransactionStyle","abstract":[{"text":"Provides the complete information of Badge Transaction Style","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BadgeTransactionStyle","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK":{"role":"collection","abstract":[],"url":"\/documentation\/onmobilegamificationsdk","title":"OnMobileGamificationSDK","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK","kind":"symbol","type":"topic"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/OnMobileGamificationSDKVersionString":{"type":"topic","kind":"symbol","title":"OnMobileGamificationSDKVersionString","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/OnMobileGamificationSDKVersionString","url":"\/documentation\/onmobilegamificationsdk\/onmobilegamificationsdkversionstring","abstract":[],"role":"symbol","fragments":[{"text":"OnMobileGamificationSDKVersionString","kind":"identifier"}]},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/AddEventRewardModel":{"navigatorTitle":[{"text":"AddEventRewardModel","kind":"identifier"}],"title":"AddEventRewardModel","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/AddEventRewardModel","role":"symbol","url":"\/documentation\/onmobilegamificationsdk\/addeventrewardmodel","abstract":[{"text":"Reward Model to trigger event with the ResultViewModel List","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AddEventRewardModel","kind":"identifier"}]},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/GamificationError":{"abstract":[{"type":"text","text":"Details of all available error types"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GamificationError"}],"kind":"symbol","title":"GamificationError","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GamificationError"}],"type":"topic","url":"\/documentation\/onmobilegamificationsdk\/gamificationerror"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/Gamification":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gamification"}],"title":"Gamification","role":"symbol","url":"\/documentation\/onmobilegamificationsdk\/gamification","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/Gamification","navigatorTitle":[{"kind":"identifier","text":"Gamification"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Parent class to interact with the OnMobileGamificationPackage"}]},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/GamificationCallBackListenerType":{"kind":"symbol","navigatorTitle":[{"text":"GamificationCallBackListenerType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationCallBackListenerType","url":"\/documentation\/onmobilegamificationsdk\/gamificationcallbacklistenertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GamificationCallBackListenerType","kind":"identifier"}],"type":"topic","title":"GamificationCallBackListenerType","abstract":[{"text":"Details of the available Callback types","type":"text"}],"role":"symbol"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/GamificationClientCallback":{"title":"GamificationClientCallback","kind":"symbol","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationClientCallback","navigatorTitle":[{"text":"GamificationClientCallback","kind":"identifier"}],"url":"\/documentation\/onmobilegamificationsdk\/gamificationclientcallback","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GamificationClientCallback","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Provides the details in details to handle on client side.","type":"text"}],"type":"topic"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/BadgeTransDetail":{"role":"symbol","url":"\/documentation\/onmobilegamificationsdk\/badgetransdetail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BadgeTransDetail"}],"navigatorTitle":[{"kind":"identifier","text":"BadgeTransDetail"}],"type":"topic","title":"BadgeTransDetail","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/BadgeTransDetail","kind":"symbol","abstract":[{"type":"text","text":"Provides the complete information of Badge Transaction Detail"}]},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/BadgeTransactionModel":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BadgeTransactionModel"}],"navigatorTitle":[{"kind":"identifier","text":"BadgeTransactionModel"}],"url":"\/documentation\/onmobilegamificationsdk\/badgetransactionmodel","title":"BadgeTransactionModel","abstract":[{"text":"Provides the complete information of Badge Transaction","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/BadgeTransactionModel"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/UserReferRegistrationModel":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserReferRegistrationModel"}],"title":"UserReferRegistrationModel","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserReferRegistrationModel"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/UserReferRegistrationModel","abstract":[{"type":"text","text":"Provides the complete detail of user referral registration"}],"url":"\/documentation\/onmobilegamificationsdk\/userreferregistrationmodel"},"doc://org.cocoapods.OnMobileGamificationSDK/documentation/OnMobileGamificationSDK/GamificationClientHandler":{"identifier":"doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/GamificationClientHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GamificationClientHandler"}],"kind":"symbol","title":"GamificationClientHandler","url":"\/documentation\/onmobilegamificationsdk\/gamificationclienthandler","abstract":[{"text":"This is a client handler class to perform the actions based on framework responses.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GamificationClientHandler"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/OnMobileGamificationSDKVersionNumber","doc:\/\/org.cocoapods.OnMobileGamificationSDK\/documentation\/OnMobileGamificationSDK\/OnMobileGamificationSDKVersionString"],"title":"Variables","generated":true,"anchor":"Variables"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}